// tcconn.idl : IDL source for tcconn
//

// This file will be processed by the MIDL tool to
// produce the type library (tcconn.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
import "tcconn_contract_i.idl";
import "netmdl_contract_i.idl";

[
	uuid(443E9B68-B76B-40DA-8579-23CBB289A4DE),
	version(1.0),
]
library tcconnLib
{
	importlib("stdole2.tlb");
};

