// tcconn.idl : IDL source for tcconn
//

// This file will be processed by the MIDL tool to
// produce the type library (tcconn.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
import "tcconn_contract_i.idl";
import "netmdl_contract_i.idl";

[
	uuid(443E9B68-B76B-40DA-8579-23CBB289A4DE),
	version(1.0),
]
library tcconnLib
{
	importlib("stdole2.tlb");

    [
        uuid(6EA78630-DC6D-4D2B-91F0-686B260F29D6)
    ]
    coclass PluginTable
    {
        [default] interface IPluginTable;
    };

    [
        uuid(7727F197-99D3-4713-A26B-2A8196C6EB5C)
    ]
    coclass TeamCityConnection
    {
        [default] interface ITeamCityConnection;
    };
};

