// tcmdl.idl : IDL source for tcmdl
//

// This file will be processed by the MIDL tool to
// produce the type library (tcmdl.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
import "tcconn_contract_i.idl";
import "objmdl_contract_i.idl";
import "viewmdl_contract_i.idl";
import "asyncmdl_contract_i.idl";

[
    object,
    uuid(C0109BFA-A495-421A-A617-2792EBE19231),
    pointer_default(unique)
]
interface IUpdateIssueService : IUnknown
{
};

[
    object,
    uuid(9F72F815-1CC9-43FD-8580-336B9BDF0E13),
    pointer_default(unique)
]
interface ITrayNotifyManager : IUnknown
{
    HRESULT Initialize(ISystrayWindow* pSystrayWindow);
    HRESULT Shutdown();
    HRESULT ResetIconToNormalIfPossible();
    HRESULT ShowBaloon(LPCTSTR lpszText, LPCTSTR lpszCaption, SystrayBalloonStyle style, UINT uTimeout);
    HRESULT ShowErrorIcon();
    HRESULT ShowNewItemsIcon();
    HRESULT ShowNormalIcon();
    HRESULT ShowUpdateIcon();
};

[
    object,
    uuid(52CC2321-28EA-42D8-AC81-5524232735C5),
    pointer_default(unique)
]
interface IUpdateViewService : IUnknown
{
    HRESULT GetTrayNotifyManager(ITrayNotifyManager** ppTrayNotifyManager);
    HRESULT ResetIcon();
};

[
	uuid(10D7F6FA-C476-4494-B30E-5CA6EA74D1B4),
	version(1.0),
]
library tcmdlLib
{
	importlib("stdole2.tlb");

    [
        uuid(6EA78630-DC6D-4D2B-91F0-686B260F29D6)
    ]
    coclass PluginTable
    {
        [default] interface IPluginTable;
    };
    [
        uuid(CA6C6762-02B5-4305-8369-017E669E81D0)
    ]
    coclass SettingsFactoryImpl
    {
        [default] interface ISettingsFactory;
    };
    [
        uuid(919DE6D7-EC71-4913-A2CA-6504C5904CFE)
    ]
    coclass UpdateIssueService
    {
        [default] interface IUpdateIssueService;
    };
    [
        uuid(2108A036-76B6-407D-BA5F-EE6DA5301A2E)
    ]
    coclass UpdateViewService
    {
        [default] interface IUpdateViewService;
    };
    [
        uuid(E422C3C7-491D-4715-A614-9ACBFD9E1B5C)
    ]
    coclass OpenJiraCommand
    {
        [default] interface IControl;
    };
    [
        uuid(AB07F1CA-589D-4F9E-85E1-0D6BB5E439B6)
    ]
    coclass TrayNotifyManager
    {
        [default] interface ITrayNotifyManager;
    };
};

